name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Test First Sentence
      id: test-first-sentence
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test First Sentence
        setup-command: ''
        command: 'sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog21Test.testFirstSentence" '
        timeout: 10
        max-score: 4
    - name: Test Shiki A
      id: test-shiki-a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Shiki A
        setup-command: ''
        command: 'sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog21Test.testShikiA" '
        timeout: 10
        max-score: 5
    - name: Test Shiki B
      id: test-shiki-b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Shiki B
        setup-command: ''
        command: 'sudo locale-gen ja_JP.UTF-8 && export LANG=ja_JP.UTF-8 && sudo update-locale
          && gradle test --tests "Prog21Test.testShikiB" '
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-FIRST-SENTENCE_RESULTS: "${{steps.test-first-sentence.outputs.result}}"
        TEST-SHIKI-A_RESULTS: "${{steps.test-shiki-a.outputs.result}}"
        TEST-SHIKI-B_RESULTS: "${{steps.test-shiki-b.outputs.result}}"
      with:
        runners: test-first-sentence,test-shiki-a,test-shiki-b
